FROM ghcr.io/graalvm/graalvm-ce:21.3.0 as graalvm
COPY . /home/app/trasier-server
WORKDIR /home/app/trasier-server
RUN ./gradlew assemble
RUN gu install native-image
RUN native-image -cp build/libs/trasier-server-*-all.jar

FROM frolvlad/alpine-glibc
EXPOSE 8000
COPY --from=graalvm /home/app/trasier-server/trasier-server .
ENTRYPOINT ["./trasier-server"]
