micronaut:
  application:
    name: trasier-server
  server:
    port: 8000
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - '*'

trasier.elastic:
  namespace: default
  hosts:
    - localhost
  port: 9200
  scheme: http
  index: default
  type: event
  cluster-name: default