micronaut:
  application:
    name: trasier-server
  server:
    port: 8000

trasier.elastic:
  namespace: default
  hosts:
    - localhost
  port: 9200
  scheme: http
  index: default
  type: event
  cluster-name: default